### ISSUE TITLE
¿Código? ¿Qué es código, todos sabemos que es código? ¿todos sabemos a que nos referimos?

### ISSUE THREAD

**Issue by son0p** [son0p/algo0ritmos#2]

**Comment by jero98772** [comment]
por codigo yo entiendo: "docuemnto con una serie de pasos escritos (o alritmos)"

https://conceptodefinicion.de/codigo/  esta pagina dan esta definicon: 
`
Un Código es una serie de símbolos que por separado no representan nada, pero al combinarlos pueden generar un lenguaje comprensible solo para aquellos quienes lo entiendan. 
`
considero que "una serie de símbolos que por separado no representan nada " es como los "pasos" ,que permite comprender el inicio y fin de quien lee el codigo , no esta solo el codigo que leen los lenguajes  de programacion ,tambien estan los mensjaes codificados o colores o sonidos
